### ISSUE TITLE
Is This Abandoned?

### ISSUE THREAD

**Issue by PhluXx1** [saif-ellafi/foundryvtt-scene-preview#1]
Is this project abandoned or can we hope to see a v9 update? Thanks for the great work.

**Comment by saif-ellafi** [comment]
Hey there @PhluXx1 it does work! I am using it!!! If it is a reason of doubt, I will release just to update the build support.

**Comment by PhluXx1** [comment]
Hi @saif-ellafi thanks for getting back to me. Yeah it may not be a bad idea to change the version on the foundry package page that way other people know it's working and still supported too. Thanks and I appreciate the work.
